# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"
[wallpaper]
custom_paths = [
    "$XDG_PICTURES_DIR/Wallpapers/"
] # List of paths to search for wallpapers
